#CATPUCCINI THEME
import = ['~/dotfiles/.config/alacritty/catppuccin-mocha.toml']

[shell]
program = "/usr/bin/fish"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"
